# Generated by Django 4.1.3 on 2022-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="broker_id",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
