# Generated by Django 4.1.3 on 2022-11-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("sold", models.BooleanField(default=False)),
                ("create_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("want_price", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                ("agreed", models.BooleanField(default=False)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.sale"
                    ),
                ),
            ],
        ),
    ]
