# Generated by Django 4.1.3 on 2022-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="flag",
            field=models.BooleanField(default=False),
        ),
    ]
