# Generated by Django 4.1.3 on 2022-11-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_bid_flag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="flag",
        ),
    ]
