# Generated by Django 4.1.3 on 2022-11-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_bid_buyer_sale_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
